[package]
name = "substrait-explain"
version = "0.1.0"
edition = "2024"

[features]
# Use a pre-built protoc binary instead of building from source. Useful for CI.
protoc = ["substrait/protoc"]

[dependencies]
chrono = "0.4.41"
pest = "2.8.0"
pest_derive = "2.8.0"
prost = "0.13.5"
substrait = "0.57.0"
thiserror = "2.0.12"
