blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/DataDog/substrait-explain/discussions
    about: For questions, discussions, or general help with substrait-explain