name: Open Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 0.3.0) or bump level (patch, minor, major)"
        required: true
        type: string

jobs:
  release-pr:
    name: Open release PR
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # 2.8.1

      - name: Install cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - uses: cargo-bins/release-pr@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
