name: Rust CI

permissions:
  contents: read
  checks: write
  statuses: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache cargo dependencies / build outputs. See
      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt -- --check

      # Also downloads dependencies etc.
      - name: Basic check
        run: cargo check --features protoc

      # Use protoc feature to build the project with a pre-built protoc binary
      - name: Lint with Clippy
        run: cargo clippy --features protoc -- -D warnings

      - name: Build
        run: cargo build --features protoc --verbose

      - name: Run tests
        run: cargo test --features protoc --verbose

      - name: Run basic_usage example
        run: cargo run --example basic_usage --features protoc --verbose

      - name: Run advanced_usage example
        run: cargo run --example advanced_usage --features serde,protoc --verbose
